package udp;

import java.awt.event.KeyEvent;


public class ClienteForm extends javax.swing.JFrame {

    private Cliente cli;
    
    /**
     * Creates new form ClientForm
     */
    public ClienteForm() {
        initComponents();
        
        this.setTitle("CLIENTE UDP");
        txtPlacar1.setEditable(false);
        txtPlacar2.setEditable(false);
        txtNomeTime1.setEditable(false);
        txtNomeTime2.setEditable(false);
        
        cli = new Cliente(txtPlacar1,txtPlacar2,txtNomeTime1,txtNomeTime2);
        cli.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPlacar1 = new javax.swing.JTextField();
        txtPlacar2 = new javax.swing.JTextField();
        txtNomeTime1 = new javax.swing.JTextField();
        txtNomeTime2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("PLACAR ELETRONICO - CLIENTE");

        txtPlacar1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txtPlacar1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlacar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacar1KeyReleased(evt);
            }
        });

        txtPlacar2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txtPlacar2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlacar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacar2ActionPerformed(evt);
            }
        });
        txtPlacar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacar2KeyReleased(evt);
            }
        });

        txtNomeTime1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNomeTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeTime1ActionPerformed(evt);
            }
        });
        txtNomeTime1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeTime1KeyReleased(evt);
            }
        });

        txtNomeTime2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNomeTime2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeTime2KeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtPlacar1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPlacar2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomeTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(txtNomeTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlacar2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlacar1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeTime2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeTime2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeTime2KeyReleased

    private void txtNomeTime1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeTime1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeTime1KeyReleased

    private void txtPlacar2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacar2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacar2KeyReleased

    private void txtPlacar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacar2ActionPerformed

    private void txtPlacar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacar1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacar1KeyReleased

    private void txtNomeTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeTime1ActionPerformed
        // TODO add your handling code here:
        
       
  
        
    }//GEN-LAST:event_txtNomeTime1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNomeTime1;
    private javax.swing.JTextField txtNomeTime2;
    private javax.swing.JTextField txtPlacar1;
    private javax.swing.JTextField txtPlacar2;
    // End of variables declaration//GEN-END:variables
}
